### ISSUE TITLE
`length(clts::ACLT)` and `num_times(clts::ACLT)` do the same thing

### ISSUE THREAD

**Issue by hematthi** [RvSpectML/RvSpectMLBase.jl#17]
https://github.com/RvSpectML/RvSpectMLBase.jl/blob/b53d04f48c70f74cdd12500f116e5252322c61e7/src/types/chunk_list.jl#L84-L87

**Comment by eford** [comment]
Thanks.  `length` is a standard function name. `num_times` helps avoid confusion.  I think I'll leave them.
